import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-navbar flex justify-between p-2 font-semibold">
          <ul className="p-2 pl-4">
            <li className="cursor-pointer">
              <Link href={"/"}>Home</Link>
            </li>
          </ul>
          <ul className="flex gap-4 p-2 pr-4">
            <li className="cursor-pointer">
              <Link href={"/about"}>About</Link>
            </li>
            <li className="cursor-pointer">
              <Link href={"/login"}>Log In</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
